import { PrismaClient } from "generated/prisma/client";
import { pgAdapter } from "~/server/db";

const prisma = new PrismaClient({ adapter: pgAdapter });

async function main() {
  console.log("Seeding tags...");
  await prisma.tag.createMany({
    data: [
      { name: "thai", slug: "thai" },
      { name: "vietnamesisch", slug: "vietnamesisch" },
      { name: "indisch", slug: "indisch" },
      { name: "koreanisch", slug: "koreanisch" },
      { name: "italienisch", slug: "italienisch" },
      { name: "griechisch", slug: "griechisch" },
      { name: "chinesisch", slug: "chinesisch" },
      { name: "afrikanisch", slug: "afrikanisch" },
      { name: "osteuropäisch", slug: "osteuropaisch" },
      { name: "japanisch", slug: "japanisch" },
      { name: "orientalisch", slug: "orientalisch" },
      { name: "mexikanisch", slug: "mexikanisch" },
      { name: "amerikanisch", slug: "amerikanisch" },
      { name: "deutsch", slug: "deutsch" },
      { name: "britisch", slug: "britisch" },
      { name: "französisch", slug: "franzosisch" },
      { name: "lateinamerikanisch", slug: "lateinamerikanisch" },
      { name: "asiatisch", slug: "asiatisch" },
      { name: "jewish", slug: "jewish" },
      { name: "european", slug: "european" },
      { name: "spanisch", slug: "spanisch" },
      { name: "portugiesisch", slug: "portugiesisch" },
      { name: "nordisch", slug: "nordisch" },
      { name: "pochieren", slug: "pochieren" },
      { name: "marinieren", slug: "marinieren" },
      { name: "dämpfen", slug: "dampfen" },
      { name: "backen", slug: "backen" },
      { name: "pürieren", slug: "purieren" },
      { name: "slow cooking", slug: "slow-cooking" },
      { name: "rösten", slug: "rosten" },
      { name: "schmoren", slug: "schmoren" },
      { name: "airfrying", slug: "airfrying" },
      { name: "einlegen", slug: "einlegen" },
      { name: "einfrieren", slug: "einfrieren" },
      { name: "braten", slug: "braten" },
      { name: "glacieren", slug: "glacieren" },
      { name: "grillen", slug: "grillen" },
      { name: "füllen", slug: "fullen" },
      { name: "backofen", slug: "backofen" },
      { name: "mikrowelle", slug: "mikrowelle" },
      { name: "anschwitzen", slug: "anschwitzen" },
      { name: "kuchen", slug: "kuchen" },
      { name: "brot", slug: "brot" },
      { name: "snack", slug: "snack" },
      { name: "cocktail", slug: "cocktail" },
      { name: "dessert", slug: "dessert" },
      { name: "suppen", slug: "suppen" },
      { name: "sandwich", slug: "sandwich" },
      { name: "pizza", slug: "pizza" },
      { name: "burger", slug: "burger" },
      { name: "vorspeise", slug: "vorspeise" },
      { name: "one-pot-gerichte", slug: "one-pot-gerichte" },
      { name: "beilagen", slug: "beilagen" },
      { name: "salat", slug: "salat" },
      { name: "nudeln", slug: "nudeln" },
      { name: "hauptgericht", slug: "hauptgericht" },
      { name: "eis", slug: "eis" },
      { name: "pies und tartes", slug: "pies-und-tartes" },
      { name: "pasta", slug: "pasta" },
      { name: "brunch", slug: "brunch" },
      { name: "frühstück", slug: "fruhstuck" },
      { name: "kaltgetränke", slug: "kaltgetranke" },
      { name: "heißgetränke", slug: "heissgetranke" },
      { name: "gratins und aufläufe", slug: "gratins-und-auflaufe" },
      { name: "getränk", slug: "getrank" },
      { name: "soßen und dips", slug: "sossen-und-dips" },
      { name: "für unterwegs", slug: "fur-unterwegs" },
      { name: "kinderfreundlich", slug: "kinderfreundlich" },
      { name: "alltagsgerichte", slug: "alltagsgerichte" },
      { name: "party food", slug: "party-food" },
      { name: "vorbereiten", slug: "vorbereiten" },
      { name: "für eine person", slug: "fur-eine-person" },
      { name: "street food", slug: "street-food" },
      { name: "wohlfühlessen", slug: "wohlfuhlessen" },
      { name: "dinner party", slug: "dinner-party" },
      { name: "fingerfood", slug: "fingerfood" },
      { name: "hochzeit", slug: "hochzeit" },
      { name: "für vier", slug: "fur-vier" },
      { name: "für zwei", slug: "fur-zwei" },
      { name: "oktoberfest", slug: "oktoberfest" },
      { name: "ostern", slug: "ostern" },
      { name: "halloween", slug: "halloween" },
      { name: "valentinstag", slug: "valentinstag" },
      { name: "chinesisches neujahr", slug: "chinesisches-neujahr" },
      { name: "weihnachten", slug: "weihnachten" },
      { name: "grillparty", slug: "grillparty" },
      { name: "veganuary", slug: "veganuary" },
      { name: "4. juli", slug: "4-juli" },
      { name: "thanksgiving", slug: "thanksgiving" },
      { name: "new-year", slug: "new-year" },
      { name: "mothers-day", slug: "mothers-day" },
      { name: "frühling", slug: "fruhling" },
      { name: "herbst", slug: "herbst" },
      { name: "sommer", slug: "sommer" },
      { name: "winter", slug: "winter" },
      { name: "vegetarisch", slug: "vegetarisch" },
      { name: "rohkost", slug: "rohkost" },
      { name: "vegan", slug: "vegan" },
      { name: "glutenfrei", slug: "glutenfrei" },
      { name: "paleo", slug: "paleo" },
      { name: "low carb", slug: "low-carb" },
      { name: "laktosefrei", slug: "laktosefrei" },
      { name: "fleischlos", slug: "fleischlos" },
      { name: "leicht", slug: "leicht" },
      {
        name: "schalentiere und meeresfrüchte",
        slug: "schalentiere-und-meeresfruchte",
      },
      { name: "superfood", slug: "superfood" },
      { name: "meeresfrüchte", slug: "meeresfruchte" },
      { name: "beeren", slug: "beeren" },
      { name: "nüsse", slug: "nusse" },
      { name: "kaffee", slug: "kaffee" },
      { name: "trockenfrüchte", slug: "trockenfruchte" },
      { name: "käse", slug: "kase" },
      { name: "antipasti", slug: "antipasti" },
      { name: "kekse", slug: "kekse" },
      { name: "veggie wunder", slug: "veggie-wunder" },
      { name: "avocado dreams", slug: "avocado-dreams" },
      { name: "gebäck und teig", slug: "geback-und-teig" },
      { name: "rind", slug: "rind" },
      { name: "fisch", slug: "fisch" },
      { name: "schwein", slug: "schwein" },
      { name: "geflügel", slug: "geflugel" },
      { name: "wurst", slug: "wurst" },
      { name: "gewürze", slug: "gewurze" },
      { name: "schokolade", slug: "schokolade" },
      { name: "curry power", slug: "curry-power" },
      { name: "pasta magie", slug: "pasta-magie" },
      { name: "seeds", slug: "seeds" },
      { name: "lamb", slug: "lamb" },
      { name: "viva la spice", slug: "viva-la-spice" },
      { name: "tofu lover", slug: "tofu-lover" },
      { name: "meat lover", slug: "meat-lover" },
      { name: "fleur de salty", slug: "fleur-de-salty" },
      { name: "früchte", slug: "fruchte" },
      { name: "pilze", slug: "pilze" },
      { name: "alkohol", slug: "alkohol" },
      { name: "sojaprodukte", slug: "sojaprodukte" },
      { name: "getreide", slug: "getreide" },
      { name: "milchprodukte", slug: "milchprodukte" },
      { name: "kräuter", slug: "krauter" },
      { name: "gemüse", slug: "gemuse" },
      { name: "candy", slug: "candy" },
      { name: "aromen reichtum", slug: "aromen-reichtum" },
      { name: "pizza party", slug: "pizza-party" },
      { name: "butterbrot, baby", slug: "butterbrot-baby" },
      { name: "dressing up", slug: "dressing-up" },
      { name: "salzig", slug: "salzig" },
      { name: "würzig", slug: "wuerzig" },
      { name: "süß", slug: "suss" },
      { name: "herzhaft", slug: "herzhaft" },
      { name: "sauer", slug: "sauer" },
      { name: "bitter", slug: "bitter" },
      { name: "2022-08", slug: "2022-08" },
      { name: "2022-09", slug: "2022-09" },
      { name: "quaese", slug: "quaese" },
      { name: "albers", slug: "albers" },
      { name: "sangrita", slug: "sangrita" },
      { name: "bauhaus besser.grillen", slug: "bauhaus-besser-grillen" },
      { name: "natumi", slug: "natumi" },
      { name: "tk besser schlafen", slug: "tk-besser-schlafen" },
      { name: "1112", slug: "1112" },
      { name: "the green mountain", slug: "the-green-mountain" },
      { name: "orangina", slug: "orangina" },
      { name: "aldi gut bio", slug: "aldi-gut-bio" },
      { name: "simply v", slug: "simply-v" },
      { name: "rauch", slug: "rauch" },
      { name: "hitchcock", slug: "hitchcock" },
      { name: "ziegenkäse aus frankreich", slug: "ziegenkase-aus-frankreich" },
      { name: "kluth easter", slug: "kluth-easter" },
      { name: "formo", slug: "formo" },
      { name: "monini", slug: "monini" },
      { name: "albi", slug: "albi" },
      { name: "enerbio", slug: "enerbio" },
      { name: "ad free", slug: "ad-free" },
      { name: "zespri", slug: "zespri" },
      { name: "mövenpick eis", slug: "movenpick-eis" },
      { name: "sodapop", slug: "sodapop" },
      { name: "ramazzotti summer", slug: "ramazzotti-summer" },
      { name: "aida", slug: "aida" },
      { name: "hennessy", slug: "hennessy" },
      { name: "ramazzotti getir", slug: "ramazzotti-getir" },
      { name: "absolut", slug: "absolut" },
      { name: "old amsterdam", slug: "old-amsterdam" },
      { name: "mövenpick wein", slug: "movenpick-wein" },
      { name: "campo viejo", slug: "campo-viejo" },
      { name: "gifflar", slug: "gifflar" },
      { name: "block house", slug: "block-house" },
      { name: "picnic", slug: "picnic" },
      { name: "byodo", slug: "byodo" },
      { name: "tupperware", slug: "tupperware" },
      { name: "bamboo garden", slug: "bamboo-garden" },
      { name: "mr. tom", slug: "mr-tom" },
      { name: "looye", slug: "looye" },
      { name: "diamant", slug: "diamant" },
      { name: "techniker krankenkasse", slug: "techniker-krankenkasse" },
      { name: "penny", slug: "penny" },
      { name: "diamant_summer", slug: "diamant-summer" },
      { name: "diamant halloween", slug: "diamant-halloween" },
      { name: "diamant christmas", slug: "diamant-christmas" },
      { name: "hochland burger", slug: "hochland-burger" },
      { name: "alpro coffee", slug: "alpro-coffee" },
      { name: "tk fittes trio", slug: "tk-fittes-trio" },
      { name: "dallmayr", slug: "dallmayr" },
      { name: "hochland", slug: "hochland" },
      { name: "grafschafter", slug: "grafschafter" },
      { name: "tk abnehmen", slug: "tk-abnehmen" },
      { name: "kluth summer", slug: "kluth-summer" },
      { name: "schweppes", slug: "schweppes" },
      { name: "guinness", slug: "guinness" },
      { name: "naturtreu", slug: "naturtreu" },
      { name: "riso gallo", slug: "riso-gallo" },
      { name: "tartex", slug: "tartex" },
      { name: "video", slug: "video" },
      { name: "confidence", slug: "confidence" },
      { name: "quick-wins", slug: "quick-wins" },
      { name: "family-style", slug: "family-style" },
      { name: "budget-bites", slug: "budget-bites" },
      { name: "inspo-package", slug: "inspo-package" },
    ],
    skipDuplicates: true, // 👈 importante
  });
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
